// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SandboxesColumns holds the columns for the "sandboxes" table.
	SandboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "started_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "ended_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "terminated"}},
		{Name: "duration_ms", Type: field.TypeInt64},
		{Name: "version", Type: field.TypeInt64},
		{Name: "global_version", Type: field.TypeInt64},
	}
	// SandboxesTable holds the schema information for the "sandboxes" table.
	SandboxesTable = &schema.Table{
		Name:       "sandboxes",
		Columns:    SandboxesColumns,
		PrimaryKey: []*schema.Column{SandboxesColumns[0]},
	}
	// StatusColumns holds the columns for the "status" table.
	StatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "terminating"}, Default: "running"},
	}
	// StatusTable holds the schema information for the "status" table.
	StatusTable = &schema.Table{
		Name:       "status",
		Columns:    StatusColumns,
		PrimaryKey: []*schema.Column{StatusColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SandboxesTable,
		StatusTable,
	}
)

func init() {
}
